solution task 02 easy
oeduardosartori/logic-challenge pull request #22
Opened 2024-08-20 00:41 UTC by guilhermedoebber

2024-08-20 12:07 UTC, byeasyco requested changes

2024-08-20 12:07 UTC, byeasyco commented on 01-exercise-easy/02-loops/loops_Dev.py
> +    for i in range(0,n):
@guilhermedoebber  o uso do `range(0, n)` é redundante, porque o valor inicial 0 é o padrão para o `range` então não é necessário adicionar ele. 

Pode ser feito desta maneira:
```suggestion
    for i in range(n):
```

2024-08-26 11:52 UTC, byeasyco approved these changes

2024-08-26 23:21 UTC, oeduardosartori approved these changes

2024-08-26 23:22 UTC, merged