Feat/enriq
oeduardosartori/logic-challenge pull request #24
Opened 2024-08-20 01:06 UTC by oenriquesartori

2024-08-20 11:43 UTC, byeasyco requested changes

2024-08-20 11:43 UTC, byeasyco commented on 01-exercise-easy/06-counting-digits-in-number/countingDigitsInNumber_Dev.py
> +    pass
Pode excluir esta linha com o `pass`
```suggestion
    
```

2024-08-20 11:43 UTC, byeasyco commented on 01-exercise-easy/06-counting-digits-in-number/countingDigitsInNumber_Dev.py
> +    lista = [0]*10
É uma boa prática utilizarmos nomes de variáveis mais específicas, neste caso poderia ser por exemplo:
```suggestion
   contagens = [0] * 10
```

Pois sabemos que é uma lista quando aberto um array para armazenar as contagens.

2024-08-20 11:43 UTC, byeasyco commented on 01-exercise-easy/07-point-counter/pointCounter_Dev.py
> +    pass
Pode retirar esta linha de código
```suggestion
   
```

2024-08-20 11:43 UTC, byeasyco commented on 01-exercise-easy/07-point-counter/pointCounter_Dev.py
> +    cascalho = 0
Novamente não ficou claro com o que foi solicitado na task o nome de sua variável.
```suggestion
    total_pontos = 0
```

2024-08-20 11:43 UTC, byeasyco commented on 01-exercise-easy/07-point-counter/pointCounter_Dev.py
> +    for c in moedas:
Visto que `C` é um tipo de moeda na task, não fica claro se adicionar `for c in moedas`.
 Poderia trocar o `C` pelo tipo = `moeda` ( que tipo de moeda das moedas do jogo o jogador recebe )
```suggestion
    for moeda in moedas:
```

2024-08-23 23:15 UTC, oeduardosartori approved these changes

2024-08-23 23:16 UTC, merged